# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PowerElite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PowerElite

  target 'PowerEliteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PowerEliteUITests' do
    # Pods for testing
  end

pod 'IQKeyboardManager'
	
pod 'SideMenu'

end
